### ISSUE TITLE
Flight error - skbio linked?

### ISSUE THREAD

**Issue by willem-stock** [rhysnewell/rosella#35]
I'm having the same error as other users recently indicated. 
Running rosella recover: `[2023-02-12T14:09:01Z ERROR bird_tool_utils::command] Error when running flight process. Exitstatus was : ExitStatus(unix_wait_status(256))
thread 'main' panicked at 'Failed to grab stderr from failed flight process', /home/conda/.cargo/registry/src/github.com-1ecc6299db9ec823/bird_tool_utils-0.3.0/src/command.rs:17:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

flight is functional (flight -h and flight bin - h work just fine)
i've updated my python in the conda env (2.7.15  -> 3.10.8) but no improvement

running flight itself: `flight bin --input rosella_bins/rosella_coverages.tsv --kmer_frequencies rosella_bins/rosella_kmer_table.tsv --assembly WS-Jos1-scaffolds500.fasta --cores 4 --output_directory rosella_flight/`

this returns `Traceback (most recent call last):
  File "//.local/bin/flight", line 8, in <module>
    sys.exit(main())
  File "//.local/lib/python3.9/site-packages/flight/flight.py", line 449, in main
    args.func(args)
  File "//.local/lib/python3.9/site-packages/flight/flight.py", line 565, in bin
    rosella = rosella_engine_constructor(args)
  File "//.local/lib/python3.9/site-packages/flight/flight.py", line 536, in rosella_engine_constructor
    from flight.rosella.rosella import Rosella
  File "//.local/lib/python3.9/site-packages/flight/rosella/rosella.py", line 48, in <module>
    from flight.rosella.validating import Validator
  File "//.local/lib/python3.9/site-packages/flight/rosella/validating.py", line 49, in <module>
    from flight.rosella.clustering import Clusterer, iterative_clustering_static, kmeans_cluster
  File "//.local/lib/python3.9/site-packages/flight/rosella/clustering.py", line 56, in <module>
    from flight.rosella.binning import Binner
  File "//.local/lib/python3.9/site-packages/flight/rosella/binning.py", line 43, in <module>
    import skbio.stats.composition
  File "//.local/lib/python3.9/site-packages/skbio/__init__.py", line 11, in <module>
    import skbio.io  # noqa
  File "//.local/lib/python3.9/site-packages/skbio/io/__init__.py", line 243, in <module>
    import_module('skbio.io.format.clustal')
  File "/usr/licensed/anaconda3/2022.10/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "//.local/lib/python3.9/site-packages/skbio/io/format/clustal.py", line 148, in <module>
    from skbio.alignment import TabularMSA
  File "//.local/lib/python3.9/site-packages/skbio/alignment/__init__.py", line 204, in <module>
    from ._pairwise import (
  File "//.local/lib/python3.9/site-packages/skbio/alignment/_pairwise.py", line 15, in <module>
    from skbio.alignment._ssw_wrapper import StripedSmithWaterman
  File "skbio/alignment/_ssw_wrapper.pyx", line 1, in init skbio.alignment._ssw_wrapper
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

kind regards

**Comment by willem-stock** [comment]
since the issue seems might be related to a compatibility, i am also attaching an overview of the environments.
Conda list:

> # Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
alsa-lib                  1.2.8                h166bdaf_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
attr                      2.5.1                h166bdaf_1    conda-forge
attrs                     22.2.0             pyh71513ae_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h166bdaf_8    conda-forge
brotli-bin                1.0.9                h166bdaf_8    conda-forge
bwa                       0.7.17               h7132678_9    bioconda
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
cachecontrol              0.11.7                     py_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cairo                     1.16.0            ha61ee94_1014    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h255011f_3    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.0.7           py310hdf3cbec_0    conda-forge
cryptography              39.0.0          py310h65dfdc0_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    0.29.33         py310heca2aa9_0    conda-forge
dbus                      1.13.6               h5008d03_3    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
exceptiongroup            1.1.0              pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                h27087fc_0    conda-forge
fftw                      3.3.10          nompi_hf0379b8_106    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.38.0          py310h5764c6d_1    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
glib                      2.74.1               h6239696_1    conda-forge
glib-tools                2.74.1               h6239696_1    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
gst-plugins-base          1.21.3               h4243ec0_1    conda-forge
gstreamer                 1.21.3               h25f0c4b_1    conda-forge
gstreamer-orc             0.4.33               h166bdaf_0    conda-forge
h5py                      3.8.0           nompi_py310ha66b2ad_101    conda-forge
harfbuzz                  6.0.0                h8e241bc_0    conda-forge
hdf5                      1.14.0          nompi_h5231ba7_102    conda-forge
hdmedians                 0.14.2          py310hde88566_3    conda-forge
htslib                    1.16                 h6bc39ce_0    bioconda
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
iniconfig                 2.0.0              pyhd8ed1ab_0    conda-forge
ipython                   8.10.0             pyh41d4057_0    conda-forge
jack                      1.9.22               h11f4161_0    conda-forge
jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h0b41bf4_3    conda-forge
k8                        0.2.5                hd03093a_2    bioconda
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4           py310hbf28c38_1    conda-forge
krb5                      1.20.1               hf9c8cef_0    conda-forge
lame                      3.100             h166bdaf_1003    conda-forge
lcms2                     2.14                 h6ed2654_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libaec                    1.0.6                hcb278e6_1    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_8    conda-forge
libbrotlidec              1.0.9                h166bdaf_8    conda-forge
libbrotlienc              1.0.9                h166bdaf_8    conda-forge
libcap                    2.66                 ha37c62d_0    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libclang                  15.0.7          default_had23c3d_1    conda-forge
libclang13                15.0.7          default_h3e3d535_1    conda-forge
libcups                   2.3.3                h36d4200_3    conda-forge
libcurl                   7.87.0               h6312ad2_0    conda-forge
libdb                     6.2.32               h9c3ff4c_0    conda-forge
libdeflate                1.13                 h166bdaf_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               h9b69904_4    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libflac                   1.4.2                h27087fc_0    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgcrypt                 1.10.1               h166bdaf_0    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libglib                   2.74.1               h606061b_1    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libgpg-error              1.46                 h620e276_0    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libllvm11                 11.1.0               he0ac6c6_5    conda-forge
libllvm15                 15.0.7               hadd5161_0    conda-forge
libnghttp2                1.51.0               hdcd2b5c_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libpq                     15.1                 h2baec63_3    conda-forge
libsndfile                1.2.0                hb75c966_0    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libssh2                   1.10.0               haa6b8db_3    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libsystemd0               252                  h2a991cd_0    conda-forge
libtiff                   4.4.0                h0e0dad5_3    conda-forge
libtool                   2.4.7                h27087fc_0    conda-forge
libudev1                  252                  h166bdaf_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.10.3               h7463322_0    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
llvmlite                  0.39.1          py310h58363a5_1    conda-forge
lockfile                  0.12.2                     py_1    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
matplotlib                3.6.3           py310hff52083_0    conda-forge
matplotlib-base           3.6.3           py310he60537e_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
minimap2                  2.24                 h7132678_1    bioconda
mpg123                    1.31.2               hcb278e6_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mysql-common              8.0.32               h14678bc_0    conda-forge
mysql-libs                8.0.32               h54cf53e_0    conda-forge
natsort                   8.2.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
nspr                      4.35                 h27087fc_0    conda-forge
nss                       3.88                 he45b914_0    conda-forge
numba                     0.56.4          py310ha5257ce_0    conda-forge
numpy                     1.23.5          py310h53a5b5f_0    conda-forge
openjpeg                  2.5.0                h7d73246_1    conda-forge
openssl                   1.1.1t               h0b41bf4_0    conda-forge
packaging                 23.0               pyhd8ed1ab_0    conda-forge
pandas                    1.5.3           py310h9b08913_0    conda-forge
parallel                  20230122             ha770c72_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
patsy                     0.5.3              pyhd8ed1ab_0    conda-forge
pcre2                     10.40                hc3806b6_0    conda-forge
perl                      5.32.1          2_h7f98852_perl5    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.2.0           py310h454ad03_3    conda-forge
pip                       23.0               pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
pluggy                    1.0.0              pyhd8ed1ab_5    conda-forge
ply                       3.11                       py_1    conda-forge
pooch                     1.6.0              pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.36             pyha770c72_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pulseaudio                16.1                 h4ab2085_1    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.14.0             pyhd8ed1ab_0    conda-forge
pynndescent               0.5.8              pyh1a96a4e_0    conda-forge
pyopenssl                 23.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.7          py310hab646b1_3    conda-forge
pyqt5-sip                 12.11.0         py310heca2aa9_3    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytest                    7.2.1              pyhd8ed1ab_0    conda-forge
python                    3.10.8          h257c98d_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    3_cp310    conda-forge
pytz                      2022.7.1           pyhd8ed1ab_0    conda-forge
qt-main                   5.15.6               h18908ee_6    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.28.2             pyhd8ed1ab_0    conda-forge
rosella                   0.4.2                h6f8cb4c_1    bioconda
samtools                  1.16.1               h6899075_1    bioconda
scikit-bio                0.5.8           py310h0a54255_1    conda-forge
scikit-learn              1.2.1           py310h209a8ca_0    conda-forge
scipy                     1.10.0          py310h8deb116_2    conda-forge
seaborn                   0.9.0                      py_2    conda-forge
setuptools                67.1.0             pyhd8ed1ab_0    conda-forge
sip                       6.7.7           py310heca2aa9_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
starcode                  1.4                  hec16e2b_2    bioconda
statsmodels               0.13.5          py310hde88566_2    conda-forge
tbb                       2021.7.0             h924138e_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tornado                   6.2             py310h5764c6d_1    conda-forge
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
tzdata                    2022g                h191b570_0    conda-forge
umap-learn                0.5.3           py310hff52083_0    conda-forge
unicodedata2              15.0.0          py310h5764c6d_0    conda-forge
urllib3                   1.24.3                     py_1    conda-forge
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
xcb-util                  0.4.0                h166bdaf_0    conda-forge
xcb-util-image            0.4.0                h166bdaf_0    conda-forge
xcb-util-keysyms          0.4.0                h166bdaf_0    conda-forge
xcb-util-renderutil       0.3.9                h166bdaf_0    conda-forge
xcb-util-wm               0.4.1                h166bdaf_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.2                h3eb15da_6    conda-forge

pip list
Package                       Version
----------------------------- ---------
appdirs                       1.4.4
asttokens                     2.2.1
attrs                         22.2.0
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
CacheControl                  0.11.7
cached-property               1.5.2
certifi                       2022.12.7
cffi                          1.15.1
charset-normalizer            2.1.1
colorama                      0.4.6
contourpy                     1.0.7
cryptography                  39.0.0
cycler                        0.11.0
Cython                        0.29.33
decorator                     5.1.1
exceptiongroup                1.1.0
executing                     1.2.0
fonttools                     4.38.0
h5py                          3.8.0
hdmedians                     0.14.2
idna                          3.4
iniconfig                     2.0.0
ipython                       8.10.0
jedi                          0.18.2
joblib                        1.2.0
kiwisolver                    1.4.4
llvmlite                      0.39.1
lockfile                      0.12.2
matplotlib                    3.6.3
matplotlib-inline             0.1.6
munkres                       1.1.4
natsort                       8.2.0
numba                         0.56.4
numpy                         1.23.5
packaging                     23.0
pandas                        1.5.3
parso                         0.8.3
patsy                         0.5.3
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.2.0
pip                           23.0
pluggy                        1.0.0
ply                           3.11
pooch                         1.6.0
prompt-toolkit                3.0.36
ptyprocess                    0.7.0
pure-eval                     0.2.2
pycparser                     2.21
Pygments                      2.14.0
pynndescent                   0.5.8
pyOpenSSL                     23.0.0
pyparsing                     3.0.9
PyQt5                         5.15.7
PyQt5-sip                     12.11.0
PySocks                       1.7.1
pytest                        7.2.1
python-dateutil               2.8.2
pytz                          2022.7.1
requests                      2.28.2
scikit-bio                    0.5.8
scikit-learn                  1.2.1
scipy                         1.10.0
seaborn                       0.9.0
setuptools                    67.1.0
sip                           6.7.7
six                           1.16.0
stack-data                    0.6.2
statsmodels                   0.13.5
threadpoolctl                 3.1.0
toml                          0.10.2
tomli                         2.0.1
tornado                       6.2
tqdm                          4.64.1
traitlets                     5.9.0
umap-learn                    0.5.3
unicodedata2                  15.0.0
urllib3                       1.24.3
wcwidth                       0.2.6
wheel                         0.38.4
>

**Comment by rhysnewell** [comment]
Hi!

So just to clarify, when you first created the conda environment you were using Python 2.7 rather than Python 3.7+? That could be the cause of the issue here, as changing between python major versions like that would definitely cause some issues. I'd recommend making a completely new environment that has only ever used python 3.7+. In addition, I would assure that the numpy version stays at or below v1.21 so it remains compatible with the current version of skbio

Cheers,
Rhys

**Comment by willem-stock** [comment]
thank you for the suggestion, but the same issue persists [numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject] when starting from a newly created environment (e.g. conda install python=3.8 numpy=1.21 scikit-bio matplotlib seaborn umap-learn numba rosella )

**Comment by rhysnewell** [comment]
Okay, judging from the scikit-bio github this has all originated because they released a maintenance patch around Christmas which is maybe causing issues. From their docs, scikit-bio=0.5.7 and numpy=1.22.3 should be compatible with each other. It lookks like you currently have scikit-bio 0.5.8 installed, so try changing up those versions

**Comment by willem-stock** [comment]
I'm afraid the issue persists, also with e.g. python=3.8 numpy=1.22.3 scikit-bio=0.5.7 . I will post a solution here if i can find one.

**Comment by rhysnewell** [comment]
An updated yaml has been provided on the main branch, but here as well for clarity:

```
channels:
  - conda-forge
  - numba
  - bioconda
  - defaults
dependencies:
  - pip
  - gcc
  - cxx-compiler
  - numba
  - numpy<=1.21
  - rosella==0.4.2
  - checkm-genome==1.1.3
  - flight-genome>=1.5.0
  - joblib==1.1.0 # For https://github.com/scikit-learn-contrib/hdbscan/pull/563 which is used by flight. Can remove when hdbscan releases past 0.8.28
  - scikit-bio>=0.5.7
  - seaborn
  - umap-learn >= 0.5.3
  - scipy <= 1.8.1
  - pandas >= 1.3
  - pynndescent >= 0.5.7
  - hdbscan >= 0.8.28
  - imageio
  - matplotlib
  - tqdm
  - tbb
  - joblib
  - pebble
  - scikit-learn==1.0.2
  - threadpoolctl
  - biopython
 ```

I've managed to get this set up to work on multiple machines so hopefully it will work for you.

**Comment by willem-stock** [comment]
thank you for the fix (i will try this as soon as possible)
