### ISSUE TITLE
error trying to use coverage info from a table

### ISSUE THREAD

**Issue by jvollme** [rhysnewell/rosella#49]
Hi, as a test of principle I wanted to check how rosella performs on a set of contigs with absolute equal coverage values for only a single sample (basically trying to see if this forces it to use only secondary criteria like nucleotide composition to bin the contigs).

I created a fake coverage table in the style of the coverage tables output by rosella in previous runs, with a column for contig name, a column for "TotalAvgDepth" and a third column for a fake coverage value of 1.000

Now I get an error during flight. Running the flight command seperately fives me this message:
```
flight bin --assembly test_contigs.fasta --input faketestcontigscoverage.tsv --kmer_frequencies rosella_bins//rosella_kmer_table.tsv --min_contig_size 1500 --min_bin_size 200000 --n_neighbors 200 --output_directory rosella_bins// --cores 8
12/09/2023 11:53:48 PM INFO: Filtering disconnected contigs...
12/09/2023 11:53:48 PM INFO: Filtering Params - Max: 3.970860, 0.087331, 22651 Min: 3.698970, 0.024399, 6189
12/09/2023 11:54:11 PM INFO: Found 608 disconnected points. 608 TNF disconnected and 0 ADP disconnected...
12/09/2023 11:54:11 PM INFO: Filtered 608 contigs...
12/09/2023 11:54:11 PM INFO: Fitting precomputed matrix using UMAP...
Traceback (most recent call last):
  File "/home/ww5070/.conda/envs/rosella5/bin/flight", line 8, in <module>
    sys.exit(main())
  File "/home/ww5070/.conda/envs/rosella5/lib/python3.10/site-packages/flight/flight.py", line 449, in main
    args.func(args)
  File "/home/ww5070/.conda/envs/rosella5/lib/python3.10/site-packages/flight/flight.py", line 566, in bin
    rosella.perform_binning(args)
  File "/home/ww5070/.conda/envs/rosella5/lib/python3.10/site-packages/flight/rosella/rosella.py", line 255, in perform_binning
    x_min = min(self.embeddings[:, 0]) - 10
TypeError: 'NoneType' object is not subscriptable
```

what could be the problem here? How could i run this test (if possible at all)?

**Comment by rhysnewell** [comment]
I can't imagine this would work very well, but if it's just for interest's sake then it can't hurt. I think there is something wrong with your coverage table, it should have five columns at a minimum containing the following info: contig name, contig length, total avg depth, sample coverage, sample variance

The names of the first three columns must also match what Rosella or CoverM would create when generating a coverage table. You can set variance to 1.0 as well and be fine

**Comment by jvollme** [comment]
hmm, still not working...
I added a column with a variance of 1.000 named exactly as the coverage column but with a "-var", exactly as the coverage file produced by standard rosella runs looks like.

The fake-coverage file now looks like this (only first ten lines shown):
```
contigName      contigLen       totalAvgDepth   fakesample1     fakesample1-var
NODE_1_length_67335_cov_62.301228       67335   1.000   1.000   1.000
NODE_2_length_60366_cov_51.438538       60366   1.000   1.000   1.000
NODE_3_length_54028_cov_15.502771       54028   1.000   1.000   1.000
NODE_4_length_47318_cov_76.245401       47318   1.000   1.000   1.000
NODE_5_length_43416_cov_93.592215       43416   1.000   1.000   1.000
NODE_6_length_40938_cov_73.777734       40938   1.000   1.000   1.000
NODE_7_length_40641_cov_40.459718       40641   1.000   1.000   1.000
NODE_8_length_38448_cov_105.685413      38448   1.000   1.000   1.000
NODE_9_length_37161_cov_57.351472       37161   1.000   1.000   1.000
```

perhaps the exact coverage file format could be given (with an example) in the docs/README? Being able to create your own coverage input from other mapping tools than coverM might be useful if people have a preference exactly how they want the coverage to be determined.

**Comment by rhysnewell** [comment]
If you send me the coverage file and test contigs I should be able to debug this fairly quickly and let you know if this kind of test is going to work or not. It might just be down to a minor formatting error or it might actually be that Rosella starts discarding all contigs because the coverage results look so weird

**Comment by asuq** [comment]
Hi @rhysnewell, 
I'm seeing the same error:
`TypeError: 'NoneType' object is not subscriptable`
when running Rosella on SRR1425961 assembled with metaSPAdes v3.15.5.

The command was:
```
rosella recover --assembly scaffolds.fasta --bam-files assembly.bam --threads 8
```

I have attached `rosella_outputs.zip`, which contains the Rosella output and `scaffolds.fasta`.
[rosella_outputs.zip](https://github.com/user-attachments/files/23887828/rosella_outputs.zip)

Environment:
- Rosella 0.5.4 (bioconda)
- scikit-learn 0.5.3 (version fixed due to #63 )
- condaforge/mambaforge:24.9.2-0

P.S. I am also encountering the "zero bins" error reported in issue #58 for other samples, and I am curious whether you plan to release an updated version.
