### ISSUE TITLE
question about the refine module of rosella

### ISSUE THREAD

**Issue by quliping** [rhysnewell/rosella#52]
Rosella is a good binning software, but I have a question about the workflow of the refine module of rosella. Is it just refine a single set of bins? Could it combine different bin sets from several binning software to a single and non redundant bin set, just like what DAS tool/binning _refiner/metawrap do? If I put all bins (e.g., bins from three different binning tools) to the input folder of rosella, will rosella choose a best version for redundant bins?

Thanks.

**Comment by rhysnewell** [comment]
Hello,

Thanks for your question. Currently, no Rosella will not choose a best result when provided output from multiple different binning programs. You can however, run rosella refine on the input and the output of `DASTool` to better those results as is done in `aviary`

I might try and include this sort of functionality in future, but it is not a priority at the moment as it is quite a complex problem to tackle.

Cheers,
Rhys

**Comment by quliping** [comment]
Thanks for your reply. I will try other bin refinement tools. But I still need your help. When I'm running:
 `rosella recover -o rosella_bins --coverage-file ./metabat_depth.txt --min-contig-size 1000 --min-bin-size 100000 
--assembly SY3.fasta --threads 32 --mapper minimap2-sr --bam-files SY3.sorted.bam `
I got some stange errors. Flight tell me it didn't found the numpy package, but you can see that the numpy was indeed installed. What wrong?

`OpenBLAS blas_thread_init: pthread_create failed for thread 127 of 128: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 2061581 max
Traceback (most recent call last):
  File "/public/apps/anaconda/envs/rosella/bin/flight", line 6, in <module>
    from flight.flight import main
  File "/public/apps/anaconda/envs/rosella/lib/python3.10/site-packages/flight/flight.py", line 22, in <module>
    from Bio import SeqIO
  File "/public/apps/anaconda/envs/rosella/lib/python3.10/site-packages/Bio/SeqIO/__init__.py", line 377, in <module>
    from Bio.Align import MultipleSeqAlignment
  File "/public/apps/anaconda/envs/rosella/lib/python3.10/site-packages/Bio/Align/__init__.py", line 33, in <module>
    raise MissingPythonDependencyError(
Bio.MissingPythonDependencyError: Please install NumPy if you want to use Bio.Align. See http://www.numpy.org/
[00:03:02] [████████████████████████████████████████]     122/122     Finished refining MAGs
[2024-02-27T05:09:09Z ERROR rosella] Recover Failed with error: Flight failed with exit code: exit status: 1
`

`rosella) [qlp@master try_Semibin]$ conda list
# packages in environment at /public/apps/anaconda/envs/rosella:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
biopython                 1.83            py310h2372a71_0    conda-forge
blas                      1.1                    openblas    conda-forge
brotli                    1.1.0                hd590300_1    conda-forge
brotli-bin                1.1.0                hd590300_1    conda-forge
brotli-python             1.1.0           py310hc6cd4ac_1    conda-forge
bwa                       0.7.17              he4a0461_11    bioconda
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.27.0               hd590300_0    conda-forge
ca-certificates           2024.2.2             hbcca054_0    conda-forge
cachecontrol              0.14.0             pyhd8ed1ab_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.2.0           py310hd41b1e2_0    conda-forge
coverm                    0.7.0                h07ea13f_0    bioconda
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
cython                    3.0.8           py310hc6cd4ac_0    conda-forge
dashing                   1.0                  h40c17d1_2    bioconda
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.0              pyhd8ed1ab_2    conda-forge
executing                 2.0.1              pyhd8ed1ab_0    conda-forge
fastani                   1.34                 h4dfc31f_1    bioconda
flight-genome             1.6.3              pyh7cba7a3_0    bioconda
fonttools                 4.49.0          py310h2372a71_0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
gsl                       2.7                  he838d99_0    conda-forge
h5py                      3.10.0          nompi_py310h65828d5_101    conda-forge
hdbscan                   0.8.33          py310h1f7b6fc_4    conda-forge
hdf5                      1.14.3          nompi_h4f84152_100    conda-forge
hdmedians                 0.14.2          py310h1f7b6fc_4    conda-forge
htslib                    1.19.1               h81da01d_1    bioconda
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.6                pyhd8ed1ab_0    conda-forge
imageio                   2.34.0             pyh4b66e23_0    conda-forge
iniconfig                 2.0.0              pyhd8ed1ab_0    conda-forge
ipython                   8.22.1             pyh707e725_0    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
joblib                    1.3.0              pyhd8ed1ab_1    conda-forge
k8                        0.2.5                hdcf5f25_4    bioconda
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.5           py310hd41b1e2_1    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
lcms2                     2.15                 h7f713cb_2    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libaec                    1.1.2                h59595ed_1    conda-forge
libblas                   3.9.0           21_linux64_openblas    conda-forge
libbrotlicommon           1.1.0                hd590300_1    conda-forge
libbrotlidec              1.1.0                hd590300_1    conda-forge
libbrotlienc              1.1.0                hd590300_1    conda-forge
libcblas                  3.9.0           21_linux64_openblas    conda-forge
libcurl                   8.5.0                hca28451_0    conda-forge
libdeflate                1.18                 h0b41bf4_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_5    conda-forge
libgfortran-ng            13.2.0               h69a702a_5    conda-forge
libgfortran5              13.2.0               ha4646dd_5    conda-forge
libgomp                   13.2.0               h807b86a_5    conda-forge
libhwloc                  2.9.3           default_h554bfaf_1009    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libjpeg-turbo             2.1.5.1              hd590300_1    conda-forge
liblapack                 3.9.0           21_linux64_openblas    conda-forge
libllvm14                 14.0.6               hcd5def8_4    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.26          pthreads_h413a1c8_0    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libsqlite                 3.45.1               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_5    conda-forge
libtiff                   4.6.0                h8b53f26_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.3.2                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.12.5               h232c23b_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
llvmlite                  0.40.1          py310h1b8f574_0    conda-forge
lockfile                  0.12.2                     py_1    conda-forge
matplotlib-base           3.8.3           py310h62c0568_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
minimap2                  2.26                 he4a0461_2    bioconda
msgpack-python            1.0.7           py310hd41b1e2_0    conda-forge
munkres                   1.0.7                      py_1    bioconda
natsort                   8.4.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  h59595ed_2    conda-forge
numba                     0.57.0          py310h0f6aa51_2    conda-forge
numpy                     1.24.0          py310h08bbf29_0    conda-forge
openblas                  0.3.26          pthreads_h7a3da1a_0    conda-forge
openjpeg                  2.5.0                h488ebb8_3    conda-forge
openssl                   3.2.1                hd590300_0    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pandas                    2.2.1           py310hcc13569_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
patsy                     0.5.6              pyhd8ed1ab_0    conda-forge
pebble                    5.0.6              pyhd8ed1ab_0    conda-forge
perl                      5.32.1          7_hd590300_perl5    conda-forge
pexpect                   4.9.0              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.0.1          py310h29da1c1_1    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
platformdirs              4.2.0              pyhd8ed1ab_0    conda-forge
pluggy                    1.4.0              pyhd8ed1ab_0    conda-forge
pooch                     1.8.1              pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.42             pyha770c72_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pygments                  2.17.2             pyhd8ed1ab_0    conda-forge
pynndescent               0.5.11             pyhca7485f_0    conda-forge
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytest                    8.0.2              pyhd8ed1ab_0    conda-forge
python                    3.10.0          h543edf9_3_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    4_cp310    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rosella                   0.5.3                h8e1a5b0_0    bioconda
samtools                  1.19.2               h50ea8bc_0    bioconda
scikit-bio                0.5.9           py310h278f3c1_0    conda-forge
scikit-learn              1.1.0           py310hffb9edd_0    conda-forge
scipy                     1.10.0          py310heeff2f4_1  
seaborn                   0.12.1               hd8ed1ab_0    conda-forge
seaborn-base              0.12.1             pyhd8ed1ab_0    conda-forge
setuptools                69.1.1             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.45.1               h2c6b66d_0    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
starcode                  1.4                  h031d066_4    bioconda
statsmodels               0.14.1          py310h1f7b6fc_0    conda-forge
tbb                       2021.11.0            h00ab1b0_1    conda-forge
threadpoolctl             3.3.0              pyhc1e730c_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tqdm                      4.66.2             pyhd8ed1ab_0    conda-forge
traitlets                 5.14.1             pyhd8ed1ab_0    conda-forge
typing_extensions         4.10.0             pyha770c72_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
umap-learn                0.5.5           py310hff52083_1    conda-forge
unicodedata2              15.1.0          py310h2372a71_0    conda-forge
urllib3                   2.2.1              pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
`

sincerely,

Lping, Qu

**Comment by rhysnewell** [comment]
Hi @quliping,

Sorry for the delayed response here, I was on holiday and missed your response. The poor performance of `rosella` is confusing, I'd like to dig a bit deeper into that if possible. Can you post the assembly statistic for your assembly? And also the rosella command that you used? 
It might be that you need to incorporate shorter contigs into the binning process, by default I think rosella only uses contigs >2500 bp but if you have a heavily fragmented assembly you may need to lower this.

@marianamnoriega I'll add log message specifying successful runs, but if you didn't see any error messages then it likely ran without issue. A single round of refinement is performed by default as part of the initial binning process, hence why you end up with some MAGs with `refined` in the name. 
You can still run further refinement on these MAGs with tools like DASTool, as is done in `aviary`. 
The number of refined bins being higher than non-refined bins is normal, not something to worry about
