### ISSUE TITLE
SKLearn Issue During Refinement

### ISSUE THREAD

**Issue by schmigle** [rhysnewell/rosella#54]
During `rosella recover`, encountered the following error immediately following attempted refinement:
```
Traceback (most recent call last):
  File "/opt/miniconda/envs/rosella/bin/flight", line 10, in <module>
    sys.exit(main())
  File "/opt/miniconda/envs/rosella/lib/python3.10/site-packages/flight/flight.py", line 465, in main
    args.func(args)
  File "/opt/miniconda/envs/rosella/lib/python3.10/site-packages/flight/flight.py", line 587, in refine
    rosella = rosella_engine_constructor(args)
  File "/opt/miniconda/envs/rosella/lib/python3.10/site-packages/flight/flight.py", line 561, in rosella_engine_constructor
    rosella = Rosella(
  File "/opt/miniconda/envs/rosella/lib/python3.10/site-packages/flight/rosella/validating.py", line 71, in __init__
    super().__init__(**kwargs)
  File "/opt/miniconda/envs/rosella/lib/python3.10/site-packages/flight/rosella/clustering.py", line 83, in __init__
    super().__init__(**kwargs)
  File "/opt/miniconda/envs/rosella/lib/python3.10/site-packages/flight/rosella/embedding.py", line 88, in __init__
    super().__init__(**kwargs)
  File "/opt/miniconda/envs/rosella/lib/python3.10/site-packages/flight/rosella/binning.py", line 163, in __init__
    self.short_sample_distance = utils.sample_distance(self.large_contigs)
  File "/opt/miniconda/envs/rosella/lib/python3.10/site-packages/flight/utils.py", line 373, in sample_distance
    return 1 - pairwise_distances(presence_absence, metric='hamming')
  File "/opt/miniconda/envs/rosella/lib/python3.10/site-packages/sklearn/metrics/pairwise.py", line 1977, in pairwise_distances
    X, Y = check_pairwise_arrays(
  File "/opt/miniconda/envs/rosella/lib/python3.10/site-packages/sklearn/metrics/pairwise.py", line 147, in check_pairwise_arrays
    X = Y = check_array(
  File "/opt/miniconda/envs/rosella/lib/python3.10/site-packages/sklearn/utils/validation.py", line 914, in check_array
    raise ValueError(
ValueError: Found array with 0 feature(s) (shape=(1, 0)) while a minimum of 1 is required by check_pairwise_arrays.
[2024-05-02T19:18:43Z ERROR rosella::refine::refinery] Run in debug mode to get full output.
[2024-05-02T19:18:43Z ERROR rosella::refine::refinery] Last message from flight: Time - 12:18:33 02-05-2024
```
I haven't counted, but I have 7 bins and this error seems to appear once for each. Here are the first few lines of the coverage file:
```
contigName	contigLen	totalAvgDepth   prokarya_QC.fastq	prokarya_QC.fastq-var
ntLink_0        170768  16.885  16.885  28.693
ntLink_1        37539   9.142   9.142   12.425
ntLink_2        87434   13.286  13.286  18.272
ntLink_3        254268  15.101  15.101  30.287
ntLink_4        244766  17.163  17.163  28.958
ntLink_5        135004  16.362  16.362  27.026
contig_1        776100  15.039  15.039  24.161
contig_11	28674   11.592  11.592  22.731
contig_12	6858    1.508   1.508   0.441
contig_14	130075  13.476  13.476  24.638
```
I didn't see any obvious issues here, except maybe that the variance is so much greater than the average in each of these cases. Any ideas?

**Comment by rhysnewell** [comment]
Hello,

Looks confusing, would you mind providing a count of how many contigs were found in your assembly and also how many contigs are in each of the bins that had the error show up?

Cheers,
Rhys

**Comment by schmigle** [comment]
Hm, I think it was 63 contigs in the assembly and each of the bins has just one contig. Probably the single binning causes the error, on further thought?

**Comment by rhysnewell** [comment]
Right, yeah I think this error is caused by the assembly being quite small. The bins shouldn't be going through refinement if they just have a single contig in them though, I will look into that.

Are you running `rosella recover` and then running `rosella refine`, or are you just running `rosella recover` by itself?

**Comment by rhysnewell** [comment]
Okay, looks like a bug. The bins shouldn't be getting to that stage when they only have a single contig, so something must be up. I'll create a fix

**Comment by CJREID** [comment]
As an added observation, these samples are also producing very few bins (and even fewer of good quality) with metabat1/2 and semibin. Single contig or otherwise, do you expect Rosella to be more conservative in recovering bins vs these other programs?

**Comment by rhysnewell** [comment]
A fix should be available in v0.5.4. As for you're second question, I'm really not sure. I'd say if the sample isn't resulting in a good assembly, none of the binners will be able to do anything

**Comment by CJREID** [comment]
Cool, will that extend to the conda version specified by aviary too? Yep, good point re: binners

**Comment by CJREID** [comment]
Sorry to drag this on but there's also a similar but slightly different error occurring for rosella refine on semibin and metabat2 outputs within aviary. MAGs being analysed by rosella refine here aren't single contig as they were above though.

```
INFO: 11:32:03 - Rosella refine iteration 0
[2024-07-17T01:32:03Z INFO  rosella] rosella version 0.5.3
[2024-07-17T01:32:08Z INFO  rosella::refine::refinery] Reading TNF table.
[2024-07-17T01:32:08Z INFO  rosella::refine::refinery] Beginning refinement of 5 MAGs
[2024-07-17T01:32:23Z ERROR rosella::refine::refinery] Last message from flight: Refining bins...
Traceback (most recent call last):
  File "/scratch3/rei219/.conda/f66cf05325a05bc6eeb3592400331d65_/bin/flight", line 10, in <module>
    sys.exit(main())
  File "/scratch3/rei219/.conda/f66cf05325a05bc6eeb3592400331d65_/lib/python3.10/site-packages/flight/flight.py", line 465, in main
    args.func(args)
  File "/scratch3/rei219/.conda/f66cf05325a05bc6eeb3592400331d65_/lib/python3.10/site-packages/flight/flight.py", line 588, in refine
    rosella.perform_refining(args)
  File "/scratch3/rei219/.conda/f66cf05325a05bc6eeb3592400331d65_/lib/python3.10/site-packages/flight/rosella/rosella.py", line 426, in perform_refining
    self.slow_refine(plots, 0, args.max_retries, x_min, x_max, y_min, y_max, False,
  File "/scratch3/rei219/.conda/f66cf05325a05bc6eeb3592400331d65_/lib/python3.10/site-packages/flight/rosella/rosella.py", line 136, in slow_refine
    plots, n = self.validate_bins(plots, n,
  File "/scratch3/rei219/.conda/f66cf05325a05bc6eeb3592400331d65_/lib/python3.10/site-packages/flight/rosella/validating.py", line 252, in validate_bins
    md_thresh, tnf_thresh, euc_thresh, agg_thresh = self.average_bin_stats(min_bin_size)
  File "/scratch3/rei219/.conda/f66cf05325a05bc6eeb3592400331d65_/lib/python3.10/site-packages/flight/rosella/validating.py", line 93, in average_bin_stats
    metrics.get_averages(np.concatenate((contigs.iloc[:, 3:].values,
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2072 and the array at index 2 has size 0
```
